$(document).on('click','#produkklik',function(){
		window.location.href='produk.php';
	}).on('click','#layananklik',function(){
		window.location.href='layanan.php';
	}).on('click','#firstslide',function(){
		window.location.href='sistemakutansi.php';
	}).on('click','#secondslide',function(){
		window.location.href='sistemantrian.php';
	}).on('click','#thirdslide',function(){
		window.location.href='palangparkir.php';
	});